# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the v1 branch
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-autolab:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deployment trigger to Autolab server
        run: |
          ssh -i {{ secrets.SSH_KEY }} jass@5.19.248.97 -p 2222 << EOF
            # if connection output contains success then:
            ls -a
            cd template-ros-core
          EOF
